# Generated by Django 4.2.14 on 2024-08-03 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='input',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='output',
        ),
        migrations.AddField(
            model_name='chat',
            name='ai',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
