# Generated by Django 4.2.14 on 2024-08-06 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0002_rename_input_chat_user_remove_chat_output_chat_ai'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table',
            old_name='end',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='table',
            old_name='start',
            new_name='start_time',
        ),
    ]
