# Generated by Django 4.2.14 on 2024-08-06 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0003_rename_end_table_end_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table',
            old_name='subject',
            new_name='topic',
        ),
        migrations.RenameField(
            model_name='table',
            old_name='name',
            new_name='user_name',
        ),
    ]
