# Generated by Django 4.2.14 on 2024-08-09 22:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assistant', '0004_rename_subject_table_topic_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='ai',
            new_name='ai_text',
        ),
        migrations.RenameField(
            model_name='table',
            old_name='user_name',
            new_name='user',
        ),
        migrations.AddField(
            model_name='chat',
            name='user_text',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chat',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
